export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link 
        href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" 
        rel="stylesheet"
      ></link>
      <title>Discord</title>
      </head>
      <body>{children}</body>
    </html>
  )
}
